export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const GITUSER_REQUEST = "GITUSER_REQUEST"
export const GITUSER_SUCCESS = "GITUSER_SUCCESS"
export const GITUSER_FAIL = "GITUSER_FAIL"

export const GITUSER_REPOS_REQUEST = "GITUSER_REPOS_REQUEST"
export const GITUSER_REPOS_SUCCESS = "GITUSER_REPOS_SUCCESS"
export const GITUSER_REPOS_FAIL = "GITUSER_REPOS_FAIL"

export const GITUSER_FOLLOWERS_REQUEST = "GITUSER_FOLLOWERS_REQUEST"
export const GITUSER_FOLLOWERS_SUCCESS = "GITUSER_FOLLOWERS_SUCCESS"
export const GITUSER_FOLLOWERS_FAIL = "GITUSER_FOLLOWERS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"